//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class admin_Employee
    {
        public admin_Employee()
        {
            this.admin_Login = new HashSet<admin_Login>();
        }
    
        public int EmpID { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        [Required]
        public Nullable<System.DateTime> DateofBirth { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        [Display(Name = "Role")]
        public string Email { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [Display(Name = "Password")]
        public string Phone { get; set; }
        [Required]
        public string Mobile { get; set; }
        [Required]
        public string PhotoPath { get; set; }

        public virtual ICollection<admin_Login> admin_Login { get; set; }
    }
}
